background = "#161a26"
foreground = "#ddd4c0"
accent = "#d4af37"
cursor = "#d4c8b4"
selection_foreground = "#f0e8d8"
selection_background = "#3d2d5e"

color0 = "#161a26"
color1 = "#b02a2a"
color2 = "#6a9a7a"
color3 = "#d4af37"
color4 = "#4a5e8a"
color5 = "#7a4aaa"
color6 = "#5a8aaa"
color7 = "#ddd4c0"
color8 = "#242e3e"
color9 = "#dd4a4a"
color10 = "#7aaa7a"
color11 = "#eac060"
color12 = "#5a7a9a"
color13 = "#9a6acc"
color14 = "#6aaacc"
color15 = "#f0e8d8"
