-- Generated by scripts/hypr2lua.
-- Source: omarchy-castlevania-theme/hyprland.conf

local activeBorderColorGold = "rgb(d4af37)"
local activeBorderColorCrimson = "rgb(b02a2a)"

hl.config({
  general = {
    col = {
      active_border = {
        colors = { activeBorderColorGold, activeBorderColorCrimson },
        angle = 45,
      },
    },
  },
  group = {
    col = {
      border_active = {
        colors = { activeBorderColorGold, activeBorderColorCrimson },
        angle = 45,
      },
    },
  },
  decoration = {
    shadow = {
      enabled = true,
      range = 16,
      render_power = 3,
      color = "rgba(0, 0, 0, 0.32)",
      offset = "2 2",
    },
  },
  animations = {
    enabled = true,
  },
})

hl.curve("expressiveFastSpatial", { type = "bezier", points = { { 0.42, 1.67 }, { 0.21, 0.90 } } })
hl.curve("expressiveSlowSpatial", { type = "bezier", points = { { 0.39, 1.29 }, { 0.35, 0.98 } } })
hl.curve("expressiveDefaultSpatial", { type = "bezier", points = { { 0.38, 1.21 }, { 0.22, 1.00 } } })
hl.curve("emphasizedDecel", { type = "bezier", points = { { 0.05, 0.70 }, { 0.10, 1.00 } } })
hl.curve("emphasizedAccel", { type = "bezier", points = { { 0.30, 0.00 }, { 0.80, 0.15 } } })
hl.curve("standardDecel", { type = "bezier", points = { { 0.00, 0.00 }, { 0.00, 1.00 } } })
hl.curve("menu_decel", { type = "bezier", points = { { 0.10, 1.00 }, { 0.00, 1.00 } } })
hl.curve("menu_accel", { type = "bezier", points = { { 0.52, 0.03 }, { 0.72, 0.08 } } })

hl.animation({
  leaf = "windowsIn",
  enabled = true,
  speed = 3,
  bezier = "emphasizedDecel",
  style = "popin",
  size = 80,
})
hl.animation({
  leaf = "windowsOut",
  enabled = true,
  speed = 2,
  bezier = "emphasizedDecel",
  style = "popin",
  size = 90,
})
hl.animation({
  leaf = "windowsMove",
  enabled = true,
  speed = 3,
  bezier = "emphasizedDecel",
  style = "slide",
})
hl.animation({
  leaf = "border",
  enabled = true,
  speed = 10,
  bezier = "emphasizedDecel",
})
hl.animation({
  leaf = "layersIn",
  enabled = true,
  speed = 2.7,
  bezier = "emphasizedDecel",
  style = "popin",
  size = 93,
})
hl.animation({
  leaf = "layersOut",
  enabled = true,
  speed = 2.4,
  bezier = "menu_accel",
  style = "popin",
  size = 94,
})
hl.animation({
  leaf = "fadeLayersIn",
  enabled = true,
  speed = 0.5,
  bezier = "menu_decel",
})
hl.animation({
  leaf = "fadeLayersOut",
  enabled = true,
  speed = 2.7,
  bezier = "menu_accel",
})
hl.animation({
  leaf = "workspaces",
  enabled = true,
  speed = 7,
  bezier = "menu_decel",
  style = "slide",
})
hl.animation({
  leaf = "specialWorkspaceIn",
  enabled = true,
  speed = 2.8,
  bezier = "emphasizedDecel",
  style = "slidevert",
})
hl.animation({
  leaf = "specialWorkspaceOut",
  enabled = true,
  speed = 1.2,
  bezier = "emphasizedAccel",
  style = "slidevert",
})
