$color = rgba(22, 26, 38, 1)
$inner_color = rgba(22, 26, 38, 1)
$outer_color = rgba(212, 175, 55, 1)
$font_color = rgba(221, 212, 192, 1)
$placeholder_color = rgba(221, 212, 192, 0.7)
$check_color = rgba(212, 175, 55, 1)
